# Generated by Django 3.2.13 on 2022-06-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
